apiVersion: v1
kind: Namespace
metadata:
  name: integration-tests
  labels:
    app: arcane-stream-mock
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: integration-tests
data:
  TEST_SECRET: c2VjcmV0IGRhdGE=
type: Opaque
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arcane-stream-mock
  namespace: integration-tests
